### ISSUE TITLE
order of dimensions among intra and inter burst must be the same

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar_slc#35]
With latest version 1.1 of our processings, the order of dimensions is not the same for coordinates (such as longitude or latitude) and for variables such as cutoff.
![image](https://user-images.githubusercontent.com/14925067/218048119-cec77eab-d910-4879-b619-902609d44993.png)

**Comment by lanougue** [comment]
Before that (which may not be a bug) It seems that xspectra are at nan values!

**Comment by lanougue** [comment]
solved with #37
