### ISSUE TITLE
cross spectrum quality first line and last line of each inter burst

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar_slc#50]
IMACS computation shows that quality of cross spectrum is probably lower on first and last line of each burst.
![image](https://user-images.githubusercontent.com/14925067/221842747-edbd9755-9c8d-47b3-ac72-fcd487cf05e8.png)
cut off (intra brust) doesn't show same issue
![image](https://user-images.githubusercontent.com/14925067/221842857-31ced85e-f332-4c90-98aa-65a14ce5ffde.png)

**Comment by agrouaze** [comment]
Looking at the sum of the ernergy depending of coordinate  `tile_line` it doesn't seem that there is a strong/systematic energy bias on first or last line of each burst:
![image](https://user-images.githubusercontent.com/14925067/223082491-f47c812d-684e-4177-b13b-56691b90050a.png)

**Comment by agrouaze** [comment]
though hypothesis of an azimuth dependent windowing applied from Level-0 to Level-1 on the signal could damp some frequencies and keep NRCS, Nv and total energy coherent.

**Comment by agrouaze** [comment]
this effect in visible only on inter burst (vv and vh):
![image](https://user-images.githubusercontent.com/14925067/223122327-9bbfaf08-b8b2-4a31-9bac-23c0eef6f3bf.png)

**Comment by lanougue** [comment]
Ok, I take this issue in charge since it is probably due to the shift between first valid sample

**Comment by lanougue** [comment]
Ok, it should be fixed with #83. @agrouaze , can you check before closing this issue ?
