### ISSUE TITLE
mitigate local incidence angle impact on cross spectrum

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar_slc#62]
A 180° error on the wave direction is observed in some WV acquisitions. 
This issue is now understood.
 It comes from the local geometry change during the radar aperture, in particular local incidence angle can change the back-scatter between the beginning and the end of the look/burst and thus the cross spectra computed between the 2 looks in absence of compensation of this effect will be interpreted as a change of phase. 
A theoretical work to describe this effect is ongoing and a  future strategy to mitigate the problem is under discussion. 
this issue impacts the cross spectrum, it can lead to error in the sign of wave direction propagation.

**Comment by lanougue** [comment]
I do not understand this issue

**Comment by lanougue** [comment]
This has nothing to do with L1B. It will be resolved in L2 processor
