### ISSUE TITLE
possible bug in the inter burst alignment

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar_slc#75]
visible streaks in the inter burst cross spectrum, probably coming from mis-alignment of the 2 overlapping bursts.

**Comment by lanougue** [comment]
A check is realized on the line direction but not on the sample direction. This bug is probably due to a pixel misalignment in the range direction. Option 1 : First valid index is different between burst, Option 2: successive burst are naturally misaligned by one pixel

**Comment by lanougue** [comment]
should be fixed with #83
