### ISSUE TITLE
possible wrong filtering of DN for low res extraction (`interface.py`)

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar_slc#76]
the filtering of sigma0 (and DN) seems much to strong at 400m resolution compare to `xsar` .
 to investigate.

**Comment by lanougue** [comment]
Filter frequency is NOT 1/gaussian_width and should be defined accordingly. Probably a sqrt(2 pi) factor to be applied.

**Comment by lanougue** [comment]
solved in #81
