### ISSUE TITLE
land flag issue

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar_slc#89]
it seems that land flag is not always correct:

all subswaths VV intra burst are OK except the IW1 top left (ie North West) in which  `False` and `True` are inverse.

![image](https://user-images.githubusercontent.com/14925067/226635795-7c85e4e4-d3d6-4e36-bbaa-72bf49deecf9.png)

**Comment by agrouaze** [comment]
![image](https://user-images.githubusercontent.com/14925067/226638603-f117c02c-0431-4b67-a860-72e8ab68d6d0.png)

**Comment by lanougue** [comment]
Ce bug est magique ! :) je vais regarder

**Comment by lanougue** [comment]
Are the xspectra available where landflag is True instead of False ?

**Comment by lanougue** [comment]
@agrouaze T'es sur de ton coup ? J'ai reprocessé l'image qui bugue en inter et en intra et le land_flag est bon chez moi

**Comment by lanougue** [comment]
I checked the *.nc file (version 1.4b) and values are good. It thus seems to  be your plot which have problem

**Comment by agrouaze** [comment]
I confirm it is only a display bug on my side. The content of the L1B file is OK.
![image](https://user-images.githubusercontent.com/14925067/227874008-a244aea3-dd2e-4a6d-856a-c1d8a1cb1c9d.png)

**Comment by agrouaze** [comment]
casting land flag into `float` solved the erroenous  `holoviews` / `bokek` map:
![image](https://user-images.githubusercontent.com/14925067/227874718-78f9cbbe-43b1-4340-afa6-be0d73b0cfcf.png)
